name: Build Vitalium FX

on:
  workflow_dispatch: # Permite lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build build-essential \
            libasound2-dev libfreetype6-dev libfftw3-dev \
            libgl1-mesa-dev libx11-dev libxext-dev \
            libxrender-dev libxcursor-dev

      - name: Configure build
        run: meson setup build --buildtype release

      - name: Build
        run: ninja -C build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vitalium-fx
          path: build
